name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'medium_converter/__init__.py'  # Only trigger on version changes
  workflow_dispatch:
    # Allow manual triggering

jobs:
  semantic-release:
    uses: ./.github/workflows/semver.yml
    permissions:
      contents: write
      id-token: write
    secrets:
      DEP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      
  create-tag-release:
    needs: semantic-release
    if: needs.semantic-release.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      
      - name: Create tag and release
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          VERSION="${{ needs.semantic-release.outputs.version }}"
          TAG="v$VERSION"
          
          echo "Creating tag $TAG for version $VERSION"
          git tag -a $TAG -m "Release $TAG"
          git push origin $TAG

  publish:
    needs: semantic-release
    if: needs.semantic-release.outputs.published == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.git-ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry build
          
      - name: Build package
        run: |
          poetry build
          
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          
  deploy-docs:
    needs: semantic-release
    if: needs.semantic-release.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.git-ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with docs
          
      - name: Build documentation
        run: |
          poetry run mkdocs build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site