name: Semantic Release
on:
  workflow_call:
    secrets:
      DEP_GITHUB_TOKEN:
        required: true
      PYPI_API_TOKEN:
        required: true
    outputs:
      published:
        value: ${{ jobs.release.outputs.published }}
      version:
        value: ${{ jobs.release.outputs.version }}
      git-ref:
        value: ${{ jobs.release.outputs.git-ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    outputs:
      published: ${{ steps.semantic.outputs.released }}
      version: ${{ steps.semantic.outputs.version }}
      git-ref: ${{ steps.semantic.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEP_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        id: semantic
        with:
          github_token: ${{ secrets.DEP_GITHUB_TOKEN }}
          # Remove force parameter as it needs to be one of: prerelease, patch, minor, major
          push: false # Don't push changes directly to main
          tag: true   # Create tags
          commit: false # Don't commit version changes
          build: true # Build the package